openapi: 3.0.1
info:
    title: Argent Bank transactions API documentation
    description: API endpoints to manage user transactions
    version: 1.0.0
servers:
    - url: http://localhost:3001/api/v1
components:
    securitySchemes:
        BearerAuth:
            type: http
            scheme: bearer
            bearerFormat: JWT
    schemas:
        Transaction:
            type: object
            properties:
                id:
                    type: string
                    description: Transaction ID
                    example: "123456"
                amount:
                    type: number
                    description: Transaction amount
                    example: 150.00
                date:
                    type: string
                    format: date
                    description: Transaction date
                    example: "2024-05-23"
                balance:
                    type: number
                    description: Account balance after transaction
                    example: 1000.00
                accountName:
                    type: string
                    description: Account for the transaction
                    example: "CB"
                description:
                    type: string
                    description: Transaction description
                    example: "Coffee"
                type:
                    type: string
                    description: Type of transaction
                    example: "electronic"
                category:
                    type: string
                    description: Category of the transaction
                    example: "food"
                note:
                    type: string
                    description: Transaction note
                    example: "Déjeuner"
security:
    - BearerAuth: []
paths:
    /transactions:
        get:
            tags:
                - View Transactions
            summary: Visualize current month transactions
            security:
                - BearerAuth: []
            responses:
                "200":
                    description: List of current month transactions
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: "#/components/schemas/Transaction"
                "401":
                    description: Unauthorized - Token missing or invalid
                "403":
                    description: Forbidden - Not allowed to access this resource
                "404":
                    description: No transactions found

    /transactions/{id}:
        get:
            tags:
                - View Transactions
            summary: Visualize transaction details
            security:
                - BearerAuth: []
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                      type: string
                  description: Transaction ID
            responses:
                "200":
                    description: Transaction details
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Transaction"
                "401":
                    description: Unauthorized - Token missing or invalid
                "403":
                    description: Forbidden - Not allowed to access this resource
                "404":
                    description: Transaction not found

    /transactions/{id}/update-category:
        patch:
            tags:
                - Update Transactions
            summary: Update transaction category
            security:
                - BearerAuth: []
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                      type: string
                  description: Transaction ID
            requestBody:
                description: New category
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                category:
                                    type: string
                                    example: "entertainment"
            responses:
                "200":
                    description: Category updated
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Transaction"
                "401":
                    description: Unauthorized - Token missing or invalid
                "403":
                    description: Forbidden - Not allowed to access this resource
                "404":
                    description: Transaction not found

    /transactions/{id}/update-note:
        patch:
            tags:
                - Update Transactions
            summary: Update transaction note
            security:
                - BearerAuth: []
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                      type: string
                  description: Transaction ID
            requestBody:
                description: New note
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                note:
                                    type: string
                                    example: "Business lunch"
            responses:
                "200":
                    description: Note updated
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Transaction"
                "401":
                    description: Unauthorized - Token missing or invalid
                "403":
                    description: Forbidden - Not allowed to access this resource
                "404":
                    description: Transaction not found
